[package]
name = "cube-ws-api"
version = "1.1.18"
edition = "2021"

[dependencies]
prost = { version = "0.11.9", default-features = false, features = [ "prost-derive" ] }

[build-dependencies]
prost-build = { version = "0.11.9", default-features = false }
