[package]
name = "cube-ws-api"
version = "1.1.18"
edition = "2021"

[features]
serde = [ "dep:serde" ]
schemars = [ "serde", "dep:schemars" ]

[dependencies]
prost = { version = "0.11.9", default-features = false, features = [ "prost-derive" ] }
serde = { version = "1", features = [ "derive" ], optional = true }

schemars = { version = "0.8.15", features = [ "preserve_order" ], optional = true }

[build-dependencies]
prost-build = { version = "0.11.9", default-features = false }
